version: '3'
services:
  redis:
    image: "redis:alpine"

  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: B4DFWh8BRiETpF7wH83JhpT4b3zPKJngYCiBJh2vxdK6h4tqNNRHnuXr7cmNQEgQ

  triviaquestions:
    image: "triviaquestions"
    ports:
      - 8080:8080

  triviabot:
    build: .
